### ISSUE TITLE
Can't import login from 1password

### ISSUE THREAD

**Issue by leshik** [jcs/rubywarden#64]
Hi,

I'm unable to import some data from 1password, here is the error (bundle gems trace stripped):
```
Traceback (most recent call last):
  from tools/1password_import.rb:253:in `<main>'
  from tools/1password_import.rb:254:in `block in <main>'
  from tools/1password_import.rb:254:in `each'
  from tools/1password_import.rb:255:in `block (2 levels) in <main>'
  from tools/1password_import.rb:255:in `each'
  from tools/1password_import.rb:257:in `block (3 levels) in <main>'
.bundle/ruby/2.5.0/gems/sqlite3-1.3.13/lib/sqlite3/statement.rb:108:in `step': SQLite3::ConstraintException: NOT NULL constraint failed: ciphers.favorite: INSERT INTO "ciphers" ("uuid", "user_uuid", "type", "data", "favorite", "name", "notes", "fields", "login", "created_at", "updated_at") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) (ActiveRecord::NotNullViolation)
```
What is it complaining about? Which one of required fields can be null?

**Comment by jcs** [comment]
`SQLite3::ConstraintException: NOT NULL constraint failed: ciphers.favorite:`

Can you try 4060f5309?
