### ISSUE TITLE
Failed to login after update

### ISSUE THREAD

**Issue by luusl** [jcs/rubywarden#76]
I've updated from bitwarden-ruby to lastest master. I followed all the migration stuff and now get an error when trying to log in.

```
[2018-09-25 16:58:17] INFO  WEBrick 1.4.2
[2018-09-25 16:58:17] INFO  ruby 2.5.1 (2018-03-29) [armv7l-linux-eabihf]
[2018-09-25 16:58:17] INFO  WEBrick::HTTPServer#start: pid=24677 port=9292
D, [2018-09-25T16:59:16.392091 #24677] DEBUG -- :   User Load (1.7ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = ? LIMIT ?  [["email", "xxx@xxx.xx"], ["LIMIT", 1]]
2018-09-25 16:59:16 - NoMethodError - undefined method `kdf_iterations' for #<User:0x01706a00>:
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/activemodel-5.1.6/lib/active_model/attribute_methods.rb:432:in `method_missing'
        /opt/rubywarden/lib/routes/api.rb:31:in `block (2 levels) in registered'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1635:in `call'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1635:in `block in compile!'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1011:in `route_eval'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1040:in `block in process_route'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1038:in `catch'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1038:in `process_route'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:990:in `block in route!'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:989:in `each'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:989:in `route!'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1097:in `block in dispatch!'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `block in invoke'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `catch'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `invoke'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1094:in `dispatch!'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:924:in `block in call!'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `block in invoke'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `catch'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `invoke'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:924:in `call!'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:913:in `call'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/rack-protection-2.0.3/lib/rack/protection/xss_header.rb:18:in `call'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/rack-protection-2.0.3/lib/rack/protection/path_traversal.rb:16:in `call'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/rack-protection-2.0.3/lib/rack/protection/json_csrf.rb:26:in `call'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/rack-protection-2.0.3/lib/rack/protection/base.rb:50:in `call'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/rack-protection-2.0.3/lib/rack/protection/base.rb:50:in `call'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/rack-protection-2.0.3/lib/rack/protection/frame_options.rb:31:in `call'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/logger.rb:15:in `call'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:224:in `call'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:194:in `call'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1958:in `call'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1502:in `block in call'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1729:in `synchronize'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1502:in `call'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/tempfile_reaper.rb:15:in `call'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/common_logger.rb:33:in `call'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:231:in `call'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/chunked.rb:54:in `call'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/content_length.rb:15:in `call'
        /opt/rubywarden/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/lib/rack/handler/webrick.rb:86:in `service'
        /usr/lib/ruby/2.5.0/webrick/httpserver.rb:140:in `service'
        /usr/lib/ruby/2.5.0/webrick/httpserver.rb:96:in `run'
        /usr/lib/ruby/2.5.0/webrick/server.rb:307:in `block in start_thread'
89.26.13.2 - - [25/Sep/2018:16:59:16 +0200] "POST /api/accounts/prelogin HTTP/1.1" 500 30 0.2874
```

**Comment by jcs** [comment]
You may need 5f3cd4cc4 but `rake db:migrate` should have created that column.

**Comment by luusl** [comment]
After running bundle exec rake db:migrate multiple times (no more messages appear when running the command) it worked. Somehow not all migrations were made when the command is called only once.
