### ISSUE TITLE
Invalid mac when importing csv

### ISSUE THREAD

**Issue by phischmi** [jcs/rubywarden#79]
Hi,
just did a fresh install of rubywarden.
When trying to import my CSV i get the following error:
`sudo -u _rubywarden env RUBYWARDEN_ENV=production bundle exec ruby tools/bitwarden_import.rb -f /home/XXX/bitwarden_export_20180924223701.csv -u XXX`

``/home/_rubywarden` is not a directory.
Bundler will use `/tmp/bundler/home/XXX' as your home directory temporarily.
master password for XXX: 
converting 1&1 FTP...
/var/www/rubywarden/lib/bitwarden.rb:150:in `decrypt': invalid mac "V[\xE5\xDAXQ\xB4t(vK\xA4\xD2\xD0\xCEr\xC1\x03\xF6\xE46Pp\xA7T\x8E\xAA\aXF\x8D\xB3" != "\n:\xF0\xCC/\x1E\x9Dv\xAA\xB9\xEEA,\x06\xC6\xF1\x13\xB4\xFBI@\nX\x18\xC1ue\xED\xB2\x91a\xE4" (RuntimeError)
	from /var/www/rubywarden/lib/user.rb:44:in `encrypt_data_with_master_password_key'
	from tools/bitwarden_import.rb:38:in `encrypt'
	from tools/bitwarden_import.rb:126:in `block in <main>'
	from /usr/lib/ruby/2.3.0/csv.rb:1748:in `each'
	from /usr/lib/ruby/2.3.0/csv.rb:1131:in `block in foreach'
	from /usr/lib/ruby/2.3.0/csv.rb:1282:in `open'
	from /usr/lib/ruby/2.3.0/csv.rb:1130:in `foreach'
	from tools/bitwarden_import.rb:103:in `<main>'`

**Comment by Joshndroid** [comment]
@jcs i am also receiving this error when importing a bitwarden exported csv

**Comment by phischmi** [comment]
I now tried several older commits going back to e6f7e9e, which was the last commit i successfully deployed on Raspbian Stretch. Now i'm on Armbian Stretch receiving the above error with each commit i tested :/

**Comment by phischmi** [comment]
Also just tried the same on my Mac using rbenv.
Same error.
So it's obviously not an OS issue...

**Comment by bahamas10** [comment]
Just ran into this error using the keepass importer.

**Comment by bahamas10** [comment]
Verified the user I created has a key starting with `2.`:

```
$ echo 'select key from users;' | sudo -u rubywarden sqlite3 db/production/production.sqlite3 
2.<snipped>
```

**Comment by jcs** [comment]
This should be fixed in d6f13b8 if you folks want to try importing again.

**Comment by phischmi** [comment]
Works!
