### ISSUE TITLE
Impossible to login

### ISSUE THREAD

**Issue by meroujanantonyan** [jcs/rubywarden#88]
Hello, 

first thank you for this project!
i use rubyvarden since 1 month and all worked fine before this morning.
I cant login anymore:

`┌(rubywarden@methamphetamine)─(pts/0)─(~/rubywarden)
└─(>) env RUBYWARDEN_ENV=production bundle exec rackup --host 0.0.0.0 -p 8080 config.ru
[2018-11-21 03:36:23] INFO  WEBrick 1.4.2
[2018-11-21 03:36:23] INFO  ruby 2.5.1 (2018-03-29) [x86_64-linux-gnu]
[2018-11-21 03:36:23] INFO  WEBrick::HTTPServer#start: pid=30428 port=8080
D, [2018-11-21T03:36:29.355865 #30428] DEBUG -- :   User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = ? LIMIT ?  [["email", "vx3r@127-0-0-1.fr"], ["LIMIT", 1]]
91.103.42.254 - - [21/Nov/2018:03:36:29 +0100] "POST /api/accounts/prelogin HTTP/1.1" 200 32 0.0532
D, [2018-11-21T03:36:29.687688 #30428] DEBUG -- :   User Load (0.1ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = ? LIMIT ?  [["email", "vx3r@127-0-0-1.fr"], ["LIMIT", 1]]
91.103.42.254 - - [21/Nov/2018:03:36:29 +0100] "POST /identity/connect/token HTTP/1.1" 400 126 0.0062
D, [2018-11-21T03:36:36.057910 #30428] DEBUG -- :   User Load (0.1ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = ? LIMIT ?  [["email", "vx3r@127-0-0-1.fr"], ["LIMIT", 1]]
91.103.42.254 - - [21/Nov/2018:03:36:36 +0100] "POST /api/accounts/prelogin HTTP/1.1" 200 32 0.0013
D, [2018-11-21T03:36:36.357373 #30428] DEBUG -- :   User Load (0.1ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = ? LIMIT ?  [["email", "vx3r@127-0-0-1.fr"], ["LIMIT", 1]]
91.103.42.254 - - [21/Nov/2018:03:36:36 +0100] "POST /identity/connect/token HTTP/1.1" 400 126 0.0014
[2018-11-21 03:36:39] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:10
        /usr/lib/ruby/2.5.0/webrick/httpserver.rb:82:in `eof?'
        /usr/lib/ruby/2.5.0/webrick/httpserver.rb:82:in `run'
        /usr/lib/ruby/2.5.0/webrick/server.rb:307:in `block in start_thread'
D, [2018-11-21T03:36:40.165529 #30428] DEBUG -- :   User Load (0.1ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = ? LIMIT ?  [["email", "vx3r@127-0-0-1.fr"], ["LIMIT", 1]]
91.103.42.254 - - [21/Nov/2018:03:36:40 +0100] "POST /api/accounts/prelogin HTTP/1.1" 200 32 0.0015
D, [2018-11-21T03:36:40.469574 #30428] DEBUG -- :   User Load (0.1ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = ? LIMIT ?  [["email", "vx3r@127-0-0-1.fr"], ["LIMIT", 1]]
91.103.42.254 - - [21/Nov/2018:03:36:40 +0100] "POST /identity/connect/token HTTP/1.1" 400 126 0.0015
[2018-11-21 03:36:40] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:10
        /usr/lib/ruby/2.5.0/webrick/httpserver.rb:82:in `eof?'
        /usr/lib/ruby/2.5.0/webrick/httpserver.rb:82:in `run'
        /usr/lib/ruby/2.5.0/webrick/server.rb:307:in `block in start_thread'`

What can be the issue ?

**Comment by meroujanantonyan** [comment]
My bad..
error_page 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415 416 417 418 420 422 423 424 426 428 429 431 444 449 450 451 500 501 502 503 504 505 506 507 508 509 510 511 /error.html;
location = /error.html {
        root /var/www/html;
        internal;
}

Dont catch all errors for api
